 export const GlobalVariable =
 Object.freeze({
     BASE_API_URL   :   'http://serveloja-s03/UNES_API/api/',
     TOKEN          :   'NgAzADYAMAA4ADMAMQA4ADcANQAxADcAMwAwADEANgAwADAAMgAwADEANgA5ADEAMAA1ADAANQAzADYAMAAtADEAOQA2ADEAOAA1ADkANgA0ADMAMAAxAC8AMAA5AC8AMgAwADEANgAgADAAOQA6ADIANQA6ADUAMQAtADEAMgAzADkAMAAxADAAMwAxADAAMAAwADIAMQAwADYAMAAzAAAA',
     VERSION        :   '0.0.1'
 });
